---

project_name: goapartment
builds:
  -
    main: ./apartment.go
    binary: goapartment
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
release:
  mode: keep-existing
